const fakerObj = {
	"address": [{
		"key": "buildingNumber",
		"value": "buildingNumber",
		"displayValue": "$address.buildingNumber"
	}, {
		"key": "cardinalDirection",
		"value": "cardinalDirection",
		"displayValue": "$address.cardinalDirection"
	}, {
		"key": "city",
		"value": "city",
		"displayValue": "$address.city"
	}, {
		"key": "cityName",
		"value": "cityName",
		"displayValue": "$address.cityName"
	}, {
		"key": "country",
		"value": "country",
		"displayValue": "$address.country"
	}, {
		"key": "countryCode",
		"value": "countryCode",
		"displayValue": "$address.countryCode"
	}, {
		"key": "county",
		"value": "county",
		"displayValue": "$address.county"
	}, {
		"key": "direction",
		"value": "direction",
		"displayValue": "$address.direction"
	}, {
		"key": "latitude",
		"value": "latitude",
		"displayValue": "$address.latitude"
	}, {
		"key": "longitude",
		"value": "longitude",
		"displayValue": "$address.longitude"
	}, {
		"key": "nearbyGPSCoordinate",
		"value": "nearbyGPSCoordinate",
		"displayValue": "$address.nearbyGPSCoordinate"
	}, {
		"key": "ordinalDirection",
		"value": "ordinalDirection",
		"displayValue": "$address.ordinalDirection"
	}, {
		"key": "secondaryAddress",
		"value": "secondaryAddress",
		"displayValue": "$address.secondaryAddress"
	}, {
		"key": "state",
		"value": "state",
		"displayValue": "$address.state"
	}, {
		"key": "stateAbbr",
		"value": "stateAbbr",
		"displayValue": "$address.stateAbbr"
	}, {
		"key": "street",
		"value": "street",
		"displayValue": "$address.street"
	}, {
		"key": "streetAddress",
		"value": "streetAddress",
		"displayValue": "$address.streetAddress"
	}, {
		"key": "streetName",
		"value": "streetName",
		"displayValue": "$address.streetName"
	}, {
		"key": "timeZone",
		"value": "timeZone",
		"displayValue": "$address.timeZone"
	}, {
		"key": "zipCode",
		"value": "zipCode",
		"displayValue": "$address.zipCode"
	}, {
		"key": "zipCodeByState",
		"value": "zipCodeByState",
		"displayValue": "$address.zipCodeByState"
	}],
	"animal": [{
		"key": "bear",
		"value": "bear",
		"displayValue": "$animal.bear"
	}, {
		"key": "bird",
		"value": "bird",
		"displayValue": "$animal.bird"
	}, {
		"key": "cat",
		"value": "cat",
		"displayValue": "$animal.cat"
	}, {
		"key": "cetacean",
		"value": "cetacean",
		"displayValue": "$animal.cetacean"
	}, {
		"key": "cow",
		"value": "cow",
		"displayValue": "$animal.cow"
	}, {
		"key": "crocodilia",
		"value": "crocodilia",
		"displayValue": "$animal.crocodilia"
	}, {
		"key": "dog",
		"value": "dog",
		"displayValue": "$animal.dog"
	}, {
		"key": "fish",
		"value": "fish",
		"displayValue": "$animal.fish"
	}, {
		"key": "horse",
		"value": "horse",
		"displayValue": "$animal.horse"
	}, {
		"key": "insect",
		"value": "insect",
		"displayValue": "$animal.insect"
	}, {
		"key": "lion",
		"value": "lion",
		"displayValue": "$animal.lion"
	}, {
		"key": "rabbit",
		"value": "rabbit",
		"displayValue": "$animal.rabbit"
	}, {
		"key": "snake",
		"value": "snake",
		"displayValue": "$animal.snake"
	}, {
		"key": "type",
		"value": "type",
		"displayValue": "$animal.type"
	}],
	"color": [{
		"key": "cmyk",
		"value": "cmyk",
		"displayValue": "$color.cmyk"
	}, {
		"key": "colorByCSSColorSpace",
		"value": "colorByCSSColorSpace",
		"displayValue": "$color.colorByCSSColorSpace"
	}, {
		"key": "cssSupportedFunction",
		"value": "cssSupportedFunction",
		"displayValue": "$color.cssSupportedFunction"
	}, {
		"key": "cssSupportedSpace",
		"value": "cssSupportedSpace",
		"displayValue": "$color.cssSupportedSpace"
	}, {
		"key": "hsl",
		"value": "hsl",
		"displayValue": "$color.hsl"
	}, {
		"key": "human",
		"value": "human",
		"displayValue": "$color.human"
	}, {
		"key": "hwb",
		"value": "hwb",
		"displayValue": "$color.hwb"
	}, {
		"key": "lab",
		"value": "lab",
		"displayValue": "$color.lab"
	}, {
		"key": "lch",
		"value": "lch",
		"displayValue": "$color.lch"
	}, {
		"key": "rgb",
		"value": "rgb",
		"displayValue": "$color.rgb"
	}, {
		"key": "space",
		"value": "space",
		"displayValue": "$color.space"
	}],
	"commerce": [{
		"key": "department",
		"value": "department",
		"displayValue": "$commerce.department"
	}, {
		"key": "price",
		"value": "price",
		"displayValue": "$commerce.price"
	}, {
		"key": "product",
		"value": "product",
		"displayValue": "$commerce.product"
	}, {
		"key": "productAdjective",
		"value": "productAdjective",
		"displayValue": "$commerce.productAdjective"
	}, {
		"key": "productDescription",
		"value": "productDescription",
		"displayValue": "$commerce.productDescription"
	}, {
		"key": "productMaterial",
		"value": "productMaterial",
		"displayValue": "$commerce.productMaterial"
	}, {
		"key": "productName",
		"value": "productName",
		"displayValue": "$commerce.productName"
	}],
	"company": [{
		"key": "bs",
		"value": "bs",
		"displayValue": "$company.bs"
	}, {
		"key": "bsAdjective",
		"value": "bsAdjective",
		"displayValue": "$company.bsAdjective"
	}, {
		"key": "bsBuzz",
		"value": "bsBuzz",
		"displayValue": "$company.bsBuzz"
	}, {
		"key": "bsNoun",
		"value": "bsNoun",
		"displayValue": "$company.bsNoun"
	}, {
		"key": "catchPhrase",
		"value": "catchPhrase",
		"displayValue": "$company.catchPhrase"
	}, {
		"key": "catchPhraseAdjective",
		"value": "catchPhraseAdjective",
		"displayValue": "$company.catchPhraseAdjective"
	}, {
		"key": "catchPhraseDescriptor",
		"value": "catchPhraseDescriptor",
		"displayValue": "$company.catchPhraseDescriptor"
	}, {
		"key": "catchPhraseNoun",
		"value": "catchPhraseNoun",
		"displayValue": "$company.catchPhraseNoun"
	}, {
		"key": "companySuffix",
		"value": "companySuffix",
		"displayValue": "$company.companySuffix"
	}, {
		"key": "name",
		"value": "name",
		"displayValue": "$company.name"
	}, {
		"key": "suffixes",
		"value": "suffixes",
		"displayValue": "$company.suffixes"
	}],
	"database": [{
		"key": "collation",
		"value": "collation",
		"displayValue": "$database.collation"
	}, {
		"key": "column",
		"value": "column",
		"displayValue": "$database.column"
	}, {
		"key": "engine",
		"value": "engine",
		"displayValue": "$database.engine"
	}, {
		"key": "mongodbObjectId",
		"value": "mongodbObjectId",
		"displayValue": "$database.mongodbObjectId"
	}, {
		"key": "type",
		"value": "type",
		"displayValue": "$database.type"
	}],
	"datatype": [{
		"key": "array",
		"value": "array",
		"displayValue": "$datatype.array"
	}, {
		"key": "bigInt",
		"value": "bigInt",
		"displayValue": "$datatype.bigInt"
	}, {
		"key": "boolean",
		"value": "boolean",
		"displayValue": "$datatype.boolean"
	}, {
		"key": "datetime",
		"value": "datetime",
		"displayValue": "$datatype.datetime"
	}, {
		"key": "float",
		"value": "float",
		"displayValue": "$datatype.float"
	}, {
		"key": "hexadecimal",
		"value": "hexadecimal",
		"displayValue": "$datatype.hexadecimal"
	}, {
		"key": "json",
		"value": "json",
		"displayValue": "$datatype.json"
	}, {
		"key": "number",
		"value": "number",
		"displayValue": "$datatype.number"
	}, {
		"key": "string",
		"value": "string",
		"displayValue": "$datatype.string"
	}, {
		"key": "uuid",
		"value": "uuid",
		"displayValue": "$datatype.uuid"
	}],
	"date": [{
		"key": "between",
		"value": "between",
		"displayValue": "$date.between"
	}, {
		"key": "betweens",
		"value": "betweens",
		"displayValue": "$date.betweens"
	}, {
		"key": "birthdate",
		"value": "birthdate",
		"displayValue": "$date.birthdate"
	}, {
		"key": "future",
		"value": "future",
		"displayValue": "$date.future"
	}, {
		"key": "month",
		"value": "month",
		"displayValue": "$date.month"
	}, {
		"key": "past",
		"value": "past",
		"displayValue": "$date.past"
	}, {
		"key": "recent",
		"value": "recent",
		"displayValue": "$date.recent"
	}, {
		"key": "soon",
		"value": "soon",
		"displayValue": "$date.soon"
	}, {
		"key": "weekday",
		"value": "weekday",
		"displayValue": "$date.weekday"
	}],
	"finance": [{
		"key": "account",
		"value": "account",
		"displayValue": "$finance.account"
	}, {
		"key": "accountName",
		"value": "accountName",
		"displayValue": "$finance.accountName"
	}, {
		"key": "amount",
		"value": "amount",
		"displayValue": "$finance.amount"
	}, {
		"key": "bic",
		"value": "bic",
		"displayValue": "$finance.bic"
	}, {
		"key": "bitcoinAddress",
		"value": "bitcoinAddress",
		"displayValue": "$finance.bitcoinAddress"
	}, {
		"key": "creditCardCVV",
		"value": "creditCardCVV",
		"displayValue": "$finance.creditCardCVV"
	}, {
		"key": "creditCardIssuer",
		"value": "creditCardIssuer",
		"displayValue": "$finance.creditCardIssuer"
	}, {
		"key": "creditCardNumber",
		"value": "creditCardNumber",
		"displayValue": "$finance.creditCardNumber"
	}, {
		"key": "currencyName",
		"value": "currencyName",
		"displayValue": "$finance.currencyName"
	}, {
		"key": "currencySymbol",
		"value": "currencySymbol",
		"displayValue": "$finance.currencySymbol"
	}, {
		"key": "ethereumAddress",
		"value": "ethereumAddress",
		"displayValue": "$finance.ethereumAddress"
	}, {
		"key": "iban",
		"value": "iban",
		"displayValue": "$finance.iban"
	}, {
		"key": "litecoinAddress",
		"value": "litecoinAddress",
		"displayValue": "$finance.litecoinAddress"
	}, {
		"key": "mask",
		"value": "mask",
		"displayValue": "$finance.mask"
	}, {
		"key": "pin",
		"value": "pin",
		"displayValue": "$finance.pin"
	}, {
		"key": "routingNumber",
		"value": "routingNumber",
		"displayValue": "$finance.routingNumber"
	}, {
		"key": "transactionDescription",
		"value": "transactionDescription",
		"displayValue": "$finance.transactionDescription"
	}, {
		"key": "transactionType",
		"value": "transactionType",
		"displayValue": "$finance.transactionType"
	}],
	"git": [{
		"key": "branch",
		"value": "branch",
		"displayValue": "$git.branch"
	}, {
		"key": "commitEntry",
		"value": "commitEntry",
		"displayValue": "$git.commitEntry"
	}, {
		"key": "commitMessage",
		"value": "commitMessage",
		"displayValue": "$git.commitMessage"
	}, {
		"key": "commitSha",
		"value": "commitSha",
		"displayValue": "$git.commitSha"
	}, {
		"key": "shortSha",
		"value": "shortSha",
		"displayValue": "$git.shortSha"
	}],
	"hacker": [{
		"key": "abbreviation",
		"value": "abbreviation",
		"displayValue": "$hacker.abbreviation"
	}, {
		"key": "adjective",
		"value": "adjective",
		"displayValue": "$hacker.adjective"
	}, {
		"key": "ingverb",
		"value": "ingverb",
		"displayValue": "$hacker.ingverb"
	}, {
		"key": "noun",
		"value": "noun",
		"displayValue": "$hacker.noun"
	}, {
		"key": "phrase",
		"value": "phrase",
		"displayValue": "$hacker.phrase"
	}, {
		"key": "verb",
		"value": "verb",
		"displayValue": "$hacker.verb"
	}],
	"helpers": [{
		"key": "arrayElement",
		"value": "arrayElement",
		"displayValue": "$helpers.arrayElement"
	}, {
		"key": "arrayElements",
		"value": "arrayElements",
		"displayValue": "$helpers.arrayElements"
	}, {
		"key": "maybe",
		"value": "maybe",
		"displayValue": "$helpers.maybe"
	}, {
		"key": "mustache",
		"value": "mustache",
		"displayValue": "$helpers.mustache"
	}, {
		"key": "objectKey",
		"value": "objectKey",
		"displayValue": "$helpers.objectKey"
	}, {
		"key": "objectValue",
		"value": "objectValue",
		"displayValue": "$helpers.objectValue"
	}, {
		"key": "regexpStyleStringParse",
		"value": "regexpStyleStringParse",
		"displayValue": "$helpers.regexpStyleStringParse"
	}, {
		"key": "replaceCreditCardSymbols",
		"value": "replaceCreditCardSymbols",
		"displayValue": "$helpers.replaceCreditCardSymbols"
	}, {
		"key": "replaceSymbolWithNumber",
		"value": "replaceSymbolWithNumber",
		"displayValue": "$helpers.replaceSymbolWithNumber"
	}, {
		"key": "replaceSymbols",
		"value": "replaceSymbols",
		"displayValue": "$helpers.replaceSymbols"
	}, {
		"key": "shuffle",
		"value": "shuffle",
		"displayValue": "$helpers.shuffle"
	}, {
		"key": "slugify",
		"value": "slugify",
		"displayValue": "$helpers.slugify"
	}, {
		"key": "uniqueArray",
		"value": "uniqueArray",
		"displayValue": "$helpers.uniqueArray"
	}],
	"image": [{
		"key": "abstract",
		"value": "abstract",
		"displayValue": "$image.abstract"
	}, {
		"key": "animals",
		"value": "animals",
		"displayValue": "$image.animals"
	}, {
		"key": "avatar",
		"value": "avatar",
		"displayValue": "$image.avatar"
	}, {
		"key": "business",
		"value": "business",
		"displayValue": "$image.business"
	}, {
		"key": "cats",
		"value": "cats",
		"displayValue": "$image.cats"
	}, {
		"key": "city",
		"value": "city",
		"displayValue": "$image.city"
	}, {
		"key": "dataUri",
		"value": "dataUri",
		"displayValue": "$image.dataUri"
	}, {
		"key": "fashion",
		"value": "fashion",
		"displayValue": "$image.fashion"
	}, {
		"key": "food",
		"value": "food",
		"displayValue": "$image.food"
	}, {
		"key": "image",
		"value": "image",
		"displayValue": "$image.image"
	}, {
		"key": "imageUrl",
		"value": "imageUrl",
		"displayValue": "$image.imageUrl"
	}, {
		"key": "nature",
		"value": "nature",
		"displayValue": "$image.nature"
	}, {
		"key": "people",
		"value": "people",
		"displayValue": "$image.people"
	}, {
		"key": "sports",
		"value": "sports",
		"displayValue": "$image.sports"
	}, {
		"key": "technics",
		"value": "technics",
		"displayValue": "$image.technics"
	}, {
		"key": "transport",
		"value": "transport",
		"displayValue": "$image.transport"
	}],
	"internet": [{
		"key": "avatar",
		"value": "avatar",
		"displayValue": "$internet.avatar"
	}, {
		"key": "color",
		"value": "color",
		"displayValue": "$internet.color"
	}, {
		"key": "domainName",
		"value": "domainName",
		"displayValue": "$internet.domainName"
	}, {
		"key": "domainSuffix",
		"value": "domainSuffix",
		"displayValue": "$internet.domainSuffix"
	}, {
		"key": "domainWord",
		"value": "domainWord",
		"displayValue": "$internet.domainWord"
	}, {
		"key": "email",
		"value": "email",
		"displayValue": "$internet.email"
	}, {
		"key": "emoji",
		"value": "emoji",
		"displayValue": "$internet.emoji"
	}, {
		"key": "exampleEmail",
		"value": "exampleEmail",
		"displayValue": "$internet.exampleEmail"
	}, {
		"key": "httpvalue",
		"value": "httpvalue",
		"displayValue": "$internet.httpvalue"
	}, {
		"key": "httpStatusCode",
		"value": "httpStatusCode",
		"displayValue": "$internet.httpStatusCode"
	}, {
		"key": "ip",
		"value": "ip",
		"displayValue": "$internet.ip"
	}, {
		"key": "ipv4",
		"value": "ipv4",
		"displayValue": "$internet.ipv4"
	}, {
		"key": "ipv6",
		"value": "ipv6",
		"displayValue": "$internet.ipv6"
	}, {
		"key": "password",
		"value": "password",
		"displayValue": "$internet.password"
	}, {
		"key": "port",
		"value": "port",
		"displayValue": "$internet.port"
	}, {
		"key": "protocol",
		"value": "protocol",
		"displayValue": "$internet.protocol"
	}, {
		"key": "url",
		"value": "url",
		"displayValue": "$internet.url"
	}, {
		"key": "userAgent",
		"value": "userAgent",
		"displayValue": "$internet.userAgent"
	}, {
		"key": "userName",
		"value": "userName",
		"displayValue": "$internet.userName"
	}],
	"lorem": [{
		"key": "lines",
		"value": "lines",
		"displayValue": "$lorem.lines"
	}, {
		"key": "paragraph",
		"value": "paragraph",
		"displayValue": "$lorem.paragraph"
	}, {
		"key": "paragraphs",
		"value": "paragraphs",
		"displayValue": "$lorem.paragraphs"
	}, {
		"key": "sentence",
		"value": "sentence",
		"displayValue": "$lorem.sentence"
	}, {
		"key": "sentences",
		"value": "sentences",
		"displayValue": "$lorem.sentences"
	}, {
		"key": "slug",
		"value": "slug",
		"displayValue": "$lorem.slug"
	}, {
		"key": "text",
		"value": "text",
		"displayValue": "$lorem.text"
	}, {
		"key": "word",
		"value": "word",
		"displayValue": "$lorem.word"
	}, {
		"key": "words",
		"value": "words",
		"displayValue": "$lorem.words"
	}],
	"music": [{
		"key": "genre",
		"value": "genre",
		"displayValue": "$music.genre"
	}, {
		"key": "songName",
		"value": "songName",
		"displayValue": "$music.songName"
	}],
	"name": [{
		"key": "fullName",
		"value": "fullName",
		"displayValue": "$name.fullName"
	}, {
		"key": "firstName",
		"value": "firstName",
		"displayValue": "$name.firstName"
	}, {
		"key": "gender",
		"value": "gender",
		"displayValue": "$name.gender"
	}, {
		"key": "jobArea",
		"value": "jobArea",
		"displayValue": "$name.jobArea"
	}, {
		"key": "jobDescriptor",
		"value": "jobDescriptor",
		"displayValue": "$name.jobDescriptor"
	}, {
		"key": "jobTitle",
		"value": "jobTitle",
		"displayValue": "$name.jobTitle"
	}, {
		"key": "jobType",
		"value": "jobType",
		"displayValue": "$name.jobType"
	}, {
		"key": "lastName",
		"value": "lastName",
		"displayValue": "$name.lastName"
	}, {
		"key": "middleName",
		"value": "middleName",
		"displayValue": "$name.middleName"
	}, {
		"key": "prefix",
		"value": "prefix",
		"displayValue": "$name.prefix"
	}, {
		"key": "suffix",
		"value": "suffix",
		"displayValue": "$name.suffix"
	}],
	"phone": [{
		"key": "imei",
		"value": "imei",
		"displayValue": "$phone.imei"
	}, {
		"key": "number",
		"value": "number",
		"displayValue": "$phone.number"
	}],
	"random": [{
		"key": "alpha",
		"value": "alpha",
		"displayValue": "$random.alpha"
	}, {
		"key": "alphaNumeric",
		"value": "alphaNumeric",
		"displayValue": "$random.alphaNumeric"
	}, {
		"key": "locale",
		"value": "locale",
		"displayValue": "$random.locale"
	}, {
		"key": "numeric",
		"value": "numeric",
		"displayValue": "$random.numeric"
	}, {
		"key": "word",
		"value": "word",
		"displayValue": "$random.word"
	}, {
		"key": "words",
		"value": "words",
		"displayValue": "$random.words"
	}],
	"science": [{
		"key": "chemicalElement",
		"value": "chemicalElement",
		"displayValue": "$science.chemicalElement"
	}, {
		"key": "unit",
		"value": "unit",
		"displayValue": "$science.unit"
	}],
	"system": [{
		"key": "commonFileExt",
		"value": "commonFileExt",
		"displayValue": "$system.commonFileExt"
	}, {
		"key": "commonFileType",
		"value": "commonFileType",
		"displayValue": "$system.commonFileType"
	}, {
		"key": "directoryPath",
		"value": "directoryPath",
		"displayValue": "$system.directoryPath"
	}, {
		"key": "fileExt",
		"value": "fileExt",
		"displayValue": "$system.fileExt"
	}, {
		"key": "fileName",
		"value": "fileName",
		"displayValue": "$system.fileName"
	}, {
		"key": "filePath",
		"value": "filePath",
		"displayValue": "$system.filePath"
	}, {
		"key": "fileType",
		"value": "fileType",
		"displayValue": "$system.fileType"
	}, {
		"key": "mimeType",
		"value": "mimeType",
		"displayValue": "$system.mimeType"
	}, {
		"key": "chemicalElement",
		"value": "chemicalElement",
		"displayValue": "$system.chemicalElement"
	}, {
		"key": "semver",
		"value": "semver",
		"displayValue": "$system.semver"
	}],
	"vehicle": [{
		"key": "bicycle",
		"value": "bicycle",
		"displayValue": "$vehicle.bicycle"
	}, {
		"key": "color",
		"value": "color",
		"displayValue": "$vehicle.color"
	}, {
		"key": "fuel",
		"value": "fuel",
		"displayValue": "$vehicle.fuel"
	}, {
		"key": "manufacturer",
		"value": "manufacturer",
		"displayValue": "$vehicle.manufacturer"
	}, {
		"key": "model",
		"value": "model",
		"displayValue": "$vehicle.model"
	}, {
		"key": "type",
		"value": "type",
		"displayValue": "$vehicle.type"
	}, {
		"key": "vehicle",
		"value": "vehicle",
		"displayValue": "$vehicle.vehicle"
	}, {
		"key": "vin",
		"value": "vin",
		"displayValue": "$vehicle.vin"
	}, {
		"key": "vrm",
		"value": "vrm",
		"displayValue": "$vehicle.vrm"
	}],
	"word": [{
		"key": "adjective",
		"value": "adjective",
		"displayValue": "$vword.adjective"
	}, {
		"key": "adverb",
		"value": "adverb",
		"displayValue": "$word.adverb"
	}, {
		"key": "conjunction",
		"value": "conjunction",
		"displayValue": "$word.conjunction"
	}, {
		"key": "interjection",
		"value": "interjection",
		"displayValue": "$word.interjection"
	}, {
		"key": "noun",
		"value": "noun",
		"displayValue": "$word.noun"
	}, {
		"key": "preposition",
		"value": "preposition",
		"displayValue": "$word.preposition"
	}, {
		"key": "verb",
		"value": "verb",
		"displayValue": "$word.verb"
	}]
}

export default fakerObj
